### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by faresbh** [inner-active/InneractiveAdSDK-iOS-Specs#1]
Hello, 
I'm trying to integrate InneractiveAdSDK via cocoapods, but apparently, the cocoapods specs are invalid as the repository 'https://github.com/inner-active/InneractiveAdSDK-iOS.git/" is not found. 
Please have a look.

**Comment by CoreySmith12xx** [comment]
:(

**Comment by 2energycell** [comment]
Hi, this is a private repository since the distribution of VAMP is solely private. You may want to contact your account manager in order to get an access. Thanks.

**Comment by 2energycell** [comment]
@faresbh @CoreySmith12xx the distribution went public: https://cocoapods.org/pods/VAMP
